# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#plugin 'cocoapods-embed-flutter'
#flutter_application_path = '../../../warren/flutter-main-app'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'app_ios2' do
  use_frameworks!
  #pub 'flutter-main-app', :git => 'https://github.com/warrenbrasil/flutter-main-app.git'
  #pub 'flutter-main-app', :path => '../../../warren/flutter-main-app'
  #pub 'not_flutter_module', :git => 'https://github.com/m-ariani/not_flutter_module.git'
  #pub 'not_flutter_module', :path => '../../../playground/not_flutter_module'
  #pub 'fm_test', :git => 'https://github.com/m-ariani/fm_test.git', :branch => 'main'
  pub 'fm_test', :path => '../../fm_test'
  #install_all_flutter_pods(flutter_application_path)
end
